# Generated by Django 5.0.4 on 2024-04-20 12:05

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_date_event_ticket_count_card_bid_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.IntegerField(default=api.utils.make_cvv),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(default=api.utils.make_card_number),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(default='Отправлена на модерацию', max_length=100),
        ),
    ]
