# Generated by Django 5.0.4 on 2024-04-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_card_cvv_alter_card_number_alter_card_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
