# Generated by Django 5.0.4 on 2024-04-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_bank_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='for_kid',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
