version: '3.3'

services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build:
      context: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/var/www/static
    depends_on:
      - backend

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  static:
  data: