# Generated by Django 5.0.4 on 2024-04-20 07:06

import datetime
import jwt_auth.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2024, 4, 20, 10, 2, 56, 830651)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default='qqq', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passport_number',
            field=jwt_auth.fields.EncryptedField(default=6020),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='passport_series',
            field=jwt_auth.fields.EncryptedField(default=999999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='+7(928)267-45-98', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
