# Generated by Django 5.0.4 on 2024-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_remove_user_middle_name_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_series',
            field=models.TextField(),
        ),
    ]
